// Test generated by RoostGPT for test deliveryManangementSya using AI Type Open AI and AI Model gpt-4

package com.company.deliverymanagement.config;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.crypto.password.PasswordEncoder;

import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.assertNotNull;

@ExtendWith(MockitoExtension.class)
public class PasswordEncoderConfig_passwordEncoder_99884512ec_Test {

    @InjectMocks
    private PasswordEncoderConfig passwordEncoderConfig;

    @Test
    public void testPasswordEncoder_notNull() {
        PasswordEncoder passwordEncoder = passwordEncoderConfig.passwordEncoder();
        assertNotNull(passwordEncoder, "PasswordEncoder should not be null");
    }

    @Test
    public void testPasswordEncoder_instanceOfBCrypt() {
        PasswordEncoder passwordEncoder = passwordEncoderConfig.passwordEncoder();
        assertTrue(passwordEncoder instanceof BCryptPasswordEncoder, "PasswordEncoder should be an instance of BCryptPasswordEncoder");
    }
}
